---
.travis.yml:
  docker_sets:
    - set: centos8-64
    - set: centos7-64
    - set: centos6-64
  secure: "lofLQkKl5ubHSolZwHJcNW8H12tL5W8X43vV6xwfQjuW+X33KLPqJUrXad9SJoXqscvtUQztjczbyrwTeN1QeNV4R4nVOQ9dbPUS1TAM7LgWAWoEhP2M5IrgbUusJbXwZxC6CL59wesK2uw+geFQimolU6jixNgRp938rBhcheqPjqtw9fLiOM3n5qE7yZej0ZyeUfn8HQ5i5epmqYGcUTAF0WDMrGST86c7ETtovZ38X30e4oQcHheOOYwpuYq9keJgAcG9OlFbd0dckfTmzjo/lxVkftNLFlvtHslO5VGMSI9tWukMdVdArNcyPInN9IujeI7vKkutKV9zqcjkaEmRUzKuBKv0SYT/Yx9qrUGp4dGzXbzgkmv2LXVBGrscq3xnS4hiJRIy++6l3xutlmThgqAWuujhu6vYYrxf7yhOY1WQWyTU7i+i7GZ39pd5h7VTls0FcFiJnRtiuTb2okHuAhCG/HsDVxb8ZfJPlc9tz73nOl9mCKgAyqjMhtEb52rQzoQHcjSJIKJN3ikAkrdYiXC6DS/PKiaCTShfnWvpSDoMqCfarR2A3zVHePsxooOLKcNCsVVuVKxrPliN25Z/EMYK8sRxtfsd4pI5S4PVIEobFI3nrC4WoN6w3hakv+mx2xCOPxLJhPCj3STyN0d7D9raQCIvPM9mZR3B2m0="
spec/spec_helper_acceptance.rb:
  unmanaged: false
