rvm:
  - 1.9.3
  - 2.0.0
script:
  - 'bundle exec puppet --version'
  - 'bundle exec rake validate'
  - 'bundle exec rake lint'
  - 'bundle exec rake spec'
env:
  matrix:
    - PUPPET_VERSION="~> 3.0"
    - PUPPET_VERSION="~> 4.0"
